In [2]:
import numpy as np

In [3]:
import time # to cehck qhich oppp is faster
size=100000
arr=np.arange(size)
arr

array([    0,     1,     2, ..., 99997, 99998, 99999], shape=(100000,))

In [4]:
resultlist= [0]*size
print(resultlist)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [5]:
# pure python
starttimepy =time.time()
for i in range(size):
    resultlist[i]=arr[i]*2 +5
endtimepy=time.time()
finaltimepy=endtimepy-starttimepy
print(finaltimepy)

0.048694610595703125


In [6]:
#numpy vectorization
starttimeNP =time.time()
answer= arr *2 +5
endtimeNP=time.time()
finaltimeNP=endtimeNP-starttimeNP
print(finaltimeNP)

0.0034608840942382812


In [7]:
speed= finaltimepy / finaltimeNP
print(f'numpy is approximately {speed:.1f}x faster')

numpy is approximately 14.1x faster


In [8]:
#mnp.random.rand(): uniform dustribution
np.random.rand(2,2) # it generates 2*2 matrix uniform distribution between 0 and 1

array([[0.73958578, 0.47562903],
       [0.9126226 , 0.17919563]])

In [9]:
normaldata=np.random.randn(2,5)# it generates normal distributed data
print(normaldata)

[[-1.10471891 -0.84227699  2.03287369  0.30407202  0.35174414]
 [ 0.66111345  0.05375061 -0.85801137  1.14787845  0.5326937 ]]


In [10]:
# above give random value but if i want to fix op at 1 time
np.random.seed(20)# it fixes random generated pattern
integers=np.random.randint(-25,10,size=(2,3))# it will generate random int values
print(integers)

[[  1 -10   6]
 [  3   1 -16]]


In [11]:
#matrix operations
A =np.array ([[1,2],
             [3,4]])
B=np.array([[5,6],
            [7,8]])
print(A * B) # element wise multi(hadamaerd product)

[[ 5 12]
 [21 32]]


In [12]:
C=np.array([[2,1],
          [1,3]])
C_inv=np.linalg.inv(C)
C_inv

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

In [13]:
D= C @ C
print(D)

[[ 5  5]
 [ 5 10]]


In [14]:
C.T #transpose

array([[2, 1],
       [1, 3]])